implement --clear and --msg, remove --hide-args

diff --git a/badash b/badash
--- a/badash
+++ b/badash
@@ -149,7 +149,6 @@ gen-wait-command-function() {
 
   # (no arguments to this function)
   # Note: it takes 4 backslashes here to generate 1 in the output(!?)
-  # TODO: initial arg for whether or not to cleanup the output?
   read -d '' func_text <<END_OF_WAIT_FUNCTION
 COLOR_FG_BOLD_GREEN='\\\\033[1;32m'
 COLOR_FG_RED='\\\\033[0;31m'
@@ -167,50 +166,48 @@ fi
 $WAIT_COMMAND_FUNC_NAME() {
   # flags
   #  --show-output (bool): always show command output
-  #  --hide-args (bool): show command name, but hide arguments (for secrets and such)
+  #  --clear (bool): TODO
+  #  --msg (string): TODO
   local more_args=0
+  local message=""
   while [ "\$more_args" == 0 ]
   do
     if [ "\$1" == "--show-output" ]
     then
       local show_output="true"
       shift
-    elif [ "\$1" == "--hide-args" ]
+    elif [ "\$1" == "--clear" ]
     then
-      local hide_args="true"
+      local clear="true"
+      shift
+    elif [ "\$1" == "--msg" ]
+    then
+      shift
+      message="\$1"
       shift
     else
       more_args=1
     fi
   done
-  # rest of the input is the command and arguments
-  if [ "\$hide_args" == "true" ]
+  # (rest of the input is the command and arguments)
+  # make sure cmd is not too wide for the terminal
+  # - 3 chars for spinner, 3 for ellipsis, 12 for time printout (estimated)
+  local max_length=\$(( COLUMNS - 18 ))
+  if [ -z "\$message" ]; then message="\$*"; fi
+  local cmd_display="\$message"
+  if [ "\${#message}" -gt "\$max_length" ]
   then
-    local cmd_display="\$1 [args hidden]"
-  else
-    # make sure cmd is not too wide for the terminal
-    # - 3 chars for spinner, 3 for ellipsis, 12 for time printout (estimated)
-    local max_length=\$(( COLUMNS - 18 ))
-    local cmd_args="\$*"
-    if [ "\${#cmd_args}" -gt "\$max_length" ]
-    then
-      local cmd_display="\${cmd_args:0:\$max_length}..."
-    else
-      local cmd_display="\$cmd_args"
-    fi
+    cmd_display="\${message:0:\$max_length}..."
   fi
+  local total_length=\$(( 3 + \${#cmd_display} ))
 
-  # calculate things for the output
   local spin_chars='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' # braille dots
   local num_chars=\${#spin_chars}
-  #local total_length=\$(( 2 + \${#cmd_display} ))
 
-  # capture when the command was started
   local cmd_start_time=\$(\$DATE_CMD +%s%3N)
 
   # start the spinner running async, and get its PID
   (
-    # wait for the command to complete, showing a busy spinner
     i=0
     while :
     do
@@ -221,14 +218,14 @@ $WAIT_COMMAND_FUNC_NAME() {
   ) & disown
   local spinner_pid="\$!"
 
-  # trap signals and kill the spinner process
-  trap "kill \$spinner_pid" INT TERM
+  # kill the spinner process for Ctrl-C, and exit this as well
+  trap "kill \$spinner_pid && exit" INT TERM
 
   # run the command, capturing its output (both stdout and stderr)
   cmd_output="\$("\$@" 2>&1)"
   local exit_code="\$?"
 
-  # clear the trap, and kill the spinner process
+  # clear the trap, and stop the spinner
   trap - INT TERM
   kill "\$spinner_pid"
 
@@ -236,14 +233,16 @@ $WAIT_COMMAND_FUNC_NAME() {
   local cmd_stop_time=\$(\$DATE_CMD +%s%3N)
   local cmd_run_time=\$((cmd_stop_time - cmd_start_time))
 
-  # TODO: attempt to clean up, depending on option (doesn't always work)
-  # but still check if it failed?
-  #printf "\\\\r%-\${total_length}s\\\\r" ' ' >&2
-
   # check that the command was successful
   if [ "\$exit_code" == 0 ]
   then
-    printf "\\\\r \${COLOR_FG_BOLD_GREEN}✔\${COLOR_RESET} \$cmd_display (\${cmd_run_time}ms)\\\\n" >&2
+    # attempt to clean up, for --clear option (best effort, this mostly works)
+    if [ -n "\$clear" ]
+    then
+      printf "\\\\r%-\${total_length}s\\\\r" ' ' >&2
+    else
+      printf "\\\\r \${COLOR_FG_BOLD_GREEN}✔\${COLOR_RESET} \$cmd_display (\${cmd_run_time}ms)\\\\n" >&2
+    fi
     # show output if configured
     if [ "\$show_output" == "true" ]; then echo "\$cmd_output"; fi
   else
