use check and X to simplify this, and make tests more explicit

diff --git a/badash b/badash
--- a/badash
+++ b/badash
@@ -151,7 +151,6 @@ gen-wait-command-function() {
   # TODO: initial arg for whether or not to cleanup the output?
   read -d '' func_text <<END_OF_WAIT_FUNCTION
 COLOR_FG_BOLD_GREEN='\\\\033[1;32m'
-COLOR_FG_GREEN='\\\\033[0;32m'
 COLOR_FG_RED='\\\\033[0;31m'
 COLOR_RESET='\\\\033[0m'
 if [ "\$(uname -s)" == 'Darwin' ]; then DATE_CMD=gdate; else DATE_CMD=date; fi
@@ -199,7 +198,7 @@ $WAIT_COMMAND_FUNC_NAME() {
     while :
     do
       i=\$(( (i + 1) % num_chars ))
-      printf "\\\\r\${spin_chars:\$i:1} \${COLOR_FG_BOLD_GREEN}running\${COLOR_RESET} '\${cmd_display}'" >&2
+      printf "\\\\r \${spin_chars:\$i:1} \${cmd_display}" >&2
       sleep 0.1
     done
   ) & disown
@@ -224,18 +223,16 @@ $WAIT_COMMAND_FUNC_NAME() {
   # but still check if it failed?
   #printf "\\\\r%-\${total_length}s\\\\r" ' ' >&2
 
-  printf "\\\\r  \${COLOR_FG_BOLD_GREEN}ran\${COLOR_RESET} '\$cmd_display' (\${cmd_run_time}ms)" >&2
-
   # check that the command was successful
   if [ "\$exit_code" == 0 ]
   then
-    printf " [\${COLOR_FG_GREEN}OK\${COLOR_RESET}]\\\\n"
+    printf "\\\\r \${COLOR_FG_BOLD_GREEN}✔\${COLOR_RESET} \$cmd_display (\${cmd_run_time}ms)\\\\n" >&2
     # show output if configured
     if [ "\$show_output" == "true" ]; then echo "\$cmd_output"; fi
   else
-    printf " [\${COLOR_FG_RED}ERROR\${COLOR_RESET}]\\\\n"
-    # if it fails, show the command output
-    echo "\$cmd_output"
+    printf "\\\\r \${COLOR_FG_RED}✖\${COLOR_RESET} \$cmd_display (\${cmd_run_time}ms)\\\\n" >&2
+    # if it fails, show the command output (in red)
+    echo -e "\${COLOR_FG_RED}\$cmd_output\${COLOR_RESET}" >&2
   fi
   # pass through the exit code of the internal command, instead of dropping it
   return "\$exit_code"
